language: cpp
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - cmake
      - libsdl2-dev
before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
script:
  - make catch
  - make
  - ./Test
